name: Compatibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compatibility-test:
    name: Compatibility Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Test standard version
      run: |
        uv sync
        uv run python -c "import woeboost; print('Standard version works')"
        uv run python -c "from woeboost import WoeLearner; print('Free-threading detected:', WoeLearner().is_freethreaded)"



