name: Compatibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  compatibility-test:
    name: Compatibility Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Test standard version
      run: |
        uv sync --group dev
        python -c "import woeboost; print('Standard version works')"
        python -c "from woeboost import WoeBoostClassifier; print('Free-threading detected:', WoeBoostClassifier().is_freethreaded)"
    
    - name: Test freethreaded extra availability
      run: |
        # Test that freethreaded extra is available (but don't install it to avoid conflicts)
        python -c "
        import tomllib
        with open('pyproject.toml', 'rb') as f:
            data = tomllib.load(f)
        if 'project' in data and 'optional-dependencies' in data['project']:
            if 'freethreaded' in data['project']['optional-dependencies']:
                print('✅ Free-threaded extra is available')
            else:
                print('❌ Free-threaded extra not found')
        else:
            print('❌ No optional dependencies found')
        "
    
    - name: Test free-threading detection
      run: |
        python -c "
        import sys
        print('Python version:', sys.version)
        print('Free-threading check:', hasattr(sys, '_is_freethreaded'))
        print('Version string check:', 'freethreaded' in sys.version.lower())
        print('Expected: Free-threading check should be False for standard Python')
        "

  dependency-check:
    name: Dependency Compatibility Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Check dependency resolution
      run: |
        # Test that standard dependencies resolve correctly
        uv sync --group dev --dry-run
        echo "✅ Standard dependencies resolve correctly"
    
    - name: Check freethreaded dependencies (dry run)
      run: |
        # Test that freethreaded dependencies would resolve correctly
        uv add --group freethreaded --dry-run
        echo "✅ Free-threaded dependencies would resolve correctly"

  cross-platform-test:
    name: Cross-platform Compatibility
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11, 3.12]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: pyproject.toml
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --group dev
    
    - name: Run basic tests
      run: |
        uv run pytest tests/unit -v -m unit --tb=short
    
    - name: Test import
      run: |
        python -c "import woeboost; print('Import successful on', '${{ matrix.os }}')"



