name: Free-threaded Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  freethreaded-test:
    name: Free-threaded Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Test freethreaded extra availability
      run: |
        # Test that freethreaded extra is available (but don't install it to avoid conflicts)
        python -c "
        import tomllib
        with open('pyproject.toml', 'rb') as f:
            data = tomllib.load(f)
        if 'dependency-groups' in data and 'freethreaded' in data['dependency-groups']:
            print('✅ Free-threaded extra is available')
        else:
            print('❌ Free-threaded extra not found')
        "
    
    - name: Test free-threading detection
      run: |
        python -c "
        import sys
        print('Python version:', sys.version)
        print('Free-threading check:', hasattr(sys, '_is_freethreaded'))
        print('Version string check:', 'freethreaded' in sys.version.lower())
        print('Expected: Free-threading check should be False for standard Python')
        "




