name: Free-threaded Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  freethreaded-test:
    name: Free-threaded Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install free-threaded Python
      run: |
        uv python install 3.13.2+freethreaded
    
    - name: Test with free-threaded Python
      run: |
        # Test free-threading detection with actual free-threaded Python
        uv run --python 3.13.2+freethreaded python -c "
        import sys
        print('Python version:', sys.version)
        print('Free-threading enabled:', getattr(sys, '_is_freethreaded', False))
        print('Version contains freethreaded:', 'freethreaded' in sys.version.lower())
        
        # Test WoeBoost free-threading detection logic
        import os
        def detect_freethreading():
            if hasattr(sys, '_is_freethreaded'):
                return sys._is_freethreaded
            return 'freethreaded' in sys.version.lower() or 'free-threading' in sys.version.lower()
        
        freethreaded_detected = detect_freethreading()
        print('WoeBoost would detect free-threading:', freethreaded_detected)
        print('✅ Free-threaded Python test completed successfully')
        "
    
    - name: Test freethreaded extra availability
      run: |
        # Test that freethreaded extra is available
        python -c "
        import tomllib
        with open('pyproject.toml', 'rb') as f:
            data = tomllib.load(f)
        if 'dependency-groups' in data and 'freethreaded' in data['dependency-groups']:
            print('✅ Free-threaded extra is available')
        else:
            print('❌ Free-threaded extra not found')
        "




